name: autoshare
description: A new Flutter project.

publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  vector_math: ^2.1.4
  flutter_map: ^8.2.2
  flutter_map_dragmarker: ^8.0.3
  geocoding: ^2.0.5
  latlong2: ^0.9.1
  http: ^1.6.0
  image_picker: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  rename_app: ^1.6.5

flutter:
  uses-material-design: true
  assets: 
    - assets/Images/


